### ISSUE TITLE
Use of clap Arg methods with flattened clap-cargo Items

### ISSUE THREAD

**Issue by pinkforest** [crate-ci/clap-cargo#27]
Am I supposed to be unable to use Arg methods alongside flatten with clap-cargo items?

**Repro**

rustup
```
stable-x86_64-unknown-linux-gnu
rustc 1.57.0 (f1edd0429 2021-11-29)

```
Cargo.toml inclusions
```
clap = { version = "3.0.5", features = ["derive", "cargo", "env", "wrap_help"] }
clap-cargo = { version = "0.8", features = ["cargo_metadata"] }
```
Boilerplate code
```rust
#[derive(Parser)]
#[clap(name = "cargo geiger")]
#[clap(about, author, version, bin_name = "cargo geiger")]
pub struct GeigerCli {
    #[clap(subcommand)]
    pub command: GeigerCommands,
}

impl GeigerCli {
    pub fn from_cli() -> Result<Self, clap::Error> {
        GeigerCli::try_parse()
    }
}
```

I would have to write it like this - repeating e.g. Workspace across Subcommand enum

```rust
#[derive(Subcommand)]
#[clap(setting(AppSettings::DeriveDisplayOrder))]
pub enum GeigerCommands {
    /// Geiger with build tree
    Build {
        #[clap(flatten)]
        workspace: clap_cargo::Workspace,
    },
    /// Geiger with test tree
    Test {
        #[clap(flatten)]
        workspace: clap_cargo::Workspace,
    }
}
```

**Instead of this**

```rust
#[derive(Subcommand)]
#[clap(setting(AppSettings::DeriveDisplayOrder))]
pub enum GeigerCommands {
    /// Geiger with build tree
    Build {
        #[clap(flatten, global(true))]
        workspace: clap_cargo::Workspace,
    },
    /// Geiger with test tree
    Test {
    }
}
```

I can write regular arguments under Subcommand but flattened entry conflicts with methods

```
error: methods are not allowed for flattened entry
  --> cargo-geiger/src/args.rs:62:16
   |
62 |         #[clap(flatten, global(true))]
   |                ^^^^^^^
```

Flatten obviously brings FromStr trait considering if I remove flatten

```
62  |         #[clap(global(true))]
    |         ^ the trait `FromStr` is not implemented for `clap_cargo::Features`
```

In order to refactor this with global() on clap-cargo items under the Subcommand enum - 

How this should be addressed with clap-cargo perhaps if this is something clap-cargo doesn't handle yet?

**Comment by epage** [comment]
> error: methods are not allowed for flattened entry

This is a `clap_derive` limitation and one unlikely to ever change because of the complexities of having derives interact with each other (only at runtime through the traits).  The only option is to not use `global` but include them on each command.

**Comment by pinkforest** [comment]
Okay so maybe I will PR a documentation on
https://github.com/clap-rs/clap/blob/v3.0.5/examples/derive_ref/README.md
Under Magic Attributes and in clap-cargo

**Comment by pinkforest** [comment]
I've raised coverage analysis here on which methods may or may not be supported in the future
https://github.com/clap-rs/clap/issues/3269

**Comment by epage** [comment]
Since this is a `clap_derive` thing, I'll go ahead and close this out
